# Generated by Django 5.2.15 on 2026-06-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('warn', 'Warning'), ('crit', 'Critical')], max_length=4)),
                ('metric', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_percent', models.FloatField()),
                ('cpu_cores', models.IntegerField()),
                ('ram_percent', models.FloatField()),
                ('ram_used', models.BigIntegerField()),
                ('ram_total', models.BigIntegerField()),
                ('disk_percent', models.FloatField()),
                ('disk_used', models.BigIntegerField()),
                ('disk_total', models.BigIntegerField()),
                ('net_bytes_sent', models.BigIntegerField()),
                ('net_bytes_recv', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
